### ISSUE TITLE
Can you set status as a variable?

### ISSUE THREAD

**Issue by asrindayananda** [InfraWay/tweet-action#1]
Hi, 
I tried setting a github action workflow variable and print this out in status but didn't work. It just printed out $SOME_VAR on my twitter status. Is it possible to print a environment variable or did I set it wrong?
Thanks in advance :)
 
```
   env:
      SOME_VAR: Stuff
      - name: TweetToTwitter
        uses: InfraWay/tweet-action@v1.0.1
        with:
          status: $SOME_VAR
```
